---

- name: copy consul-bootstrap script
  ansible.builtin.copy:
    src: consul-bootstrap
    dest: /opt/consul/bin/consul-bootstrap
    mode: 0750
    owner: consul
    group: consul
  tags:
    - consul-bootstrap

- name: create consul-bootstrap service
  ansible.builtin.template: src=templates/consul-bootstrap.service.j2 dest=/usr/lib/systemd/system/consul-bootstrap.service owner=root group=root mode=0644
  notify:
    - consul daemon-reload

- name: create directory for systemd drop-ins
  ansible.builtin.file:
    path: /etc/systemd/system/consul-bootstrap.service.d
    state: directory
    mode: 0755
