---

- name: copy consul-online script
  ansible.builtin.copy:
    src: consul-online
    dest: /opt/consul/bin/consul-online
    mode: '0750'
    owner: consul
    group: consul

- name: copy consul-bootstrap script
  ansible.builtin.copy:
    src: consul-bootstrap
    dest: /opt/consul/bin/consul-bootstrap
    mode: '0750'
    owner: consul
    group: consul

- name: create consul-online service
  template: src=templates/consul-online.service.j2 dest=/etc/systemd/system/consul-online.service owner=root group=root mode=0644
  notify:
    - consul daemon-reload

- name: create consul-bootstrap service
  template: src=templates/consul-bootstrap.service.j2 dest=/etc/systemd/system/consul-bootstrap.service owner=root group=root mode=0644
  notify:
    - consul daemon-reload

- name: create consul-online target
  template: src=templates/consul-online.target.j2 dest=/etc/systemd/system/consul-online.target owner=root group=root mode=0644
  notify:
    - consul daemon-reload

- name: create directory for systemd drop-ins
  file:
    path: /etc/systemd/system/consul-bootstrap.service.d
    state: directory
    mode: 0755
