---

- name: install dependencies
  package:
    name: "{{ packages }}"
  vars:
    packages:
      - curl
      - unzip
      - jq

- name: consul group
  ansible.builtin.group:
    name: consul
    state: present
    system: true

- name: consul user
  ansible.builtin.user:
    name: consul
    group: consul
    system: true
    create_home: false

- name: copy temporary install-consul script
  ansible.builtin.copy:
    src: install-consul
    dest: /tmp/install-consul
    mode: 0750
  changed_when: false

- name: run install-consul script
  ansible.builtin.shell: bash /tmp/install-consul --version {{ consul_version }}
  args:
    chdir: /
    creates: /opt/consul/bin/consul

- name: delete temporary install-consul script
  ansible.builtin.file:
    path: /tmp/install-consul
    state: absent
  changed_when: false

- name: copy run-consul script
  ansible.builtin.copy:
    src: run-consul
    dest: /opt/consul/bin/run-consul
    mode: 0750
    owner: consul
    group: consul
  tags:
    - run-consul

- name: chcon consul binary
  ansible.builtin.file:
    path: /opt/consul/bin/consul
    owner: consul
    group: consul
    mode: 0755
    setype: bin_t
    seuser: system_u

- name: consul kresd.conf.d files
  template:
    src: kresd-policy-consul.conf.j2
    dest: /etc/knot-resolver/kresd.conf.d/810-policy-consul.conf
    owner: root
    group: knot-resolver
    mode: 0640

- name: create directory for systemd drop-ins
  file:
    path: /etc/systemd/system/consul.service.d
    owner: root
    group: root
    state: directory
    mode: 0755

- name: create consul service
  template: src=templates/consul.service.j2 dest=/usr/lib/systemd/system/consul.service owner=root group=root mode=0644
  notify:
    - consul daemon-reload

- name: copy consul-online script
  ansible.builtin.copy:
    src: consul-online
    dest: /opt/consul/bin/consul-online
    mode: 0750
    owner: consul
    group: consul

- name: create consul-online service
  template: src=templates/consul-online.service.j2 dest=/usr/lib/systemd/system/consul-online.service owner=root group=root mode=0644
  notify:
    - consul daemon-reload

- name: create consul-online target
  template: src=templates/consul-online.target.j2 dest=/usr/lib/systemd/system/consul-online.target owner=root group=root mode=0644
  notify:
    - consul daemon-reload

- include_tasks: consul-server.yml
  when: consul_server | bool is true

- include_tasks: health-check.yml
  when: consul_health_check | bool is true

- include_tasks: storage-setup.yml
  when: (storage_setup_physical_device is defined) and (storage_setup_physical_device | length > 0) and (consul_volume|bool)
