---

- name: install dependencies
  package:
    name: "{{ packages }}"
  vars:
    packages:
     - curl
     - unzip
     - jq

- name: consul group
  ansible.builtin.group:
    name: consul
    state: present
    system: true

- name: consul user
  ansible.builtin.user:
    name: consul
    group: consul
    system: true

- name: copy temporary install-consul script
  ansible.builtin.copy:
    src: install-consul
    dest: /tmp/install-consul
    mode: "0644"
  changed_when: false

- name: copy certificates
  ansible.builtin.copy:
    src:  "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
  loop:
    - { src: "{{ consul_ca_file_path }}", dest: "{{ consul_remote_ca_file_path }}" }
    - { src: "{{ consul_cert_file_path }}", dest: "{{ consul_remote_cert_file_path }}" }
    - { src: "{{ consul_key_file_path }}", dest: "{{ consul_remote_key_file_path }}" }
  changed_when: false

- name: run install-consul script
  ansible.builtin.shell: bash /tmp/install-consul --version {{ consul_version }} --ca-file-path {{ consul_remote_ca_file_path }} --cert-file-path {{ consul_remote_cert_file_path }} --key-file-path {{ consul_remote_key_file_path }}
  args:
    chdir: /
    creates: /opt/consul/bin/consul

- name: delete temporary install-consul script
  ansible.builtin.file:
    path: /tmp/install-consul
    state: absent
  changed_when: false

- name: delete certificates
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ consul_remote_ca_file_path }}"
    - "{{ consul_remote_cert_file_path }}"
    - "{{ consul_remote_key_file_path }}"
  changed_when: false

- name: copy run-consul script
  ansible.builtin.copy:
    src: run-consul
    dest: /opt/consul/bin/run-consul
    mode: '0755'
    owner: consul
    group: consul
