---

- name: create temporary directory
  file:
    path: /tmp/health-check
    owner: "root"
    group: "root"
    state: directory
    mode: 0700
  changed_when: false

- name: unarchive consul health check
  ansible.builtin.unarchive:
    src: "{{ consul_health_check_url }}"
    dest: /tmp/health-check
    owner: root
    group: root
    mode: "0755"
    remote_src: yes
  changed_when: false

- name: move health-check
  ansible.builtin.copy:
    src: /tmp/health-check/consulate
    dest: /opt/consul/bin/consul-health-check
    owner: consul
    group: consul
    mode: "0755"
    remote_src: yes
  changed_when: false

- name: remove temporary directory
  ansible.builtin.file:
    path: /tmp/health-check
    state: absent
  changed_when: false

- name: create consul health check service
  template: src=templates/consul-health-check.service.j2 dest=/etc/systemd/system/consul-health-check.service owner=root group=root mode=0644
  notify:
    - consul daemon-reload

- name: enable consul health check on boot
  service: name=consul-health-check enabled=yes
