---

- name: create the consul ferm conf files
  ansible.builtin.template:
    src: templates/ferm-consul-health-check.conf.j2
    dest: /etc/ferm/ferm.d/1010-consul-health-check.conf
    owner: root
    group: root
    mode: 0600

- name: create temporary directory
  ansible.builtin.file:
    path: /tmp/health-check
    owner: "root"
    group: "root"
    state: directory
    mode: 0700
  changed_when: false

- name: unarchive consul health check
  ansible.builtin.unarchive:
    src: "{{ consul_health_check_url }}"
    dest: /tmp/health-check
    owner: root
    group: root
    mode: 0755
    remote_src: true
  changed_when: false

- name: move health-check
  ansible.builtin.copy:
    src: /tmp/health-check/consulate
    dest: /opt/consul/bin/consul-health-check
    owner: consul
    group: consul
    mode: 0755
    remote_src: true
  changed_when: false

- name: remove temporary directory
  ansible.builtin.file:
    path: /tmp/health-check
    state: absent
  changed_when: false

- name: create consul health check service
  ansible.builtin.template:
    src: templates/consul-health-check.service.j2
    dest: /etc/systemd/system/consul-health-check.service
    owner: root
    group: root
    mode: 0644
  notify:
    - consul daemon-reload

- name: enable consul health check on boot
  ansible.builtin.service:
    name: consul-health-check
    enabled: true
