---
- ansible.builtin.include_tasks: consul.yml
  when: ansible_os_family == "RedHat"
  tags:
    - run-consul
    - consul-bootstrap
    - consul-snapshot

- ansible.builtin.include_tasks: consul-terraform-sync.yml
  when: ansible_os_family == "RedHat" and consul_terraform_sync | bool
  tags:
    - consul-terraform-sync
    - run-consul-terraform-sync

- ansible.builtin.include_tasks: consul-template.yml
  when: ansible_os_family == "RedHat" and consul_template | bool
  tags:
    - consul-template

- ansible.builtin.include_tasks: consul-esm.yml
  when: ansible_os_family == "RedHat" and consul_esm | bool
  tags:
    - consul-esm
    - run-consul-esm
