---

# - name: check consul variables
#   assert:
#     that:
#       - consul_ca_file_path is string and consul_ca_file_path | length > 0
#       - consul_cert_file_path is string and consul_cert_file_path | length > 0
#       - consul_key_file_path is string and consul_key_file_path | length > 0
#     quiet: true

- include_tasks: consul.yml
  when: ansible_os_family == "RedHat"
  tags:
    - run-consul
    - consul-bootstrap

- include_tasks: consul-terraform-sync.yml
  when: consul_terraform_sync | bool
  tags:
    - consul-terraform-sync
    - run-consul-terraform-sync
