---

- name: systemd drop-in for options
  template:
    src:  "consul-service-storage-options.conf.j2"
    dest: "/etc/systemd/system/consul.service.d/020-storage-options.conf"
    mode: 0644

- name: /opt/consul/data directory
  file:
    path: /opt/consul/data
    state: directory
    owner: consul
    group: consul
    mode: '0700'

- name: consul storage configuration
  template:
    src: storage-setup-consul.conf.j2
    dest: /etc/filesystems.d/30-consul.conf
    mode: 0644
